USE SSAFY_USER;

CREATE TABLE IF NOT EXISTS `TEACHER` (
  `TEACHER_CODE` varchar(20) PRIMARY KEY NOT NULL,
  `GROUP_TEACHER_ID` varchar(20) NOT NULL,
  `GROUP_TEACHER_NAME` varchar(20) NOT NULL,
  `GROUP_TEACHER_HP` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE IF NOT EXISTS `PROJECT`(
  `TEAM_CODE` varchar(20) PRIMARY KEY NOT NULL,
  `TEAM_NAME` varchar(100),
  `PROJECT_NAME` varchar(100),
  `LEADER_CODE` varchar(20),
  `GRADE` varchar(20)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE IF NOT EXISTS `STUDENT` (
  `STUDENT_CODE` varchar(20) PRIMARY KEY NOT NULL,
  `TEACHER_CODE` varchar(20) NOT NULL,
  `TEAM_CODE` varchar(20),
  `STUDENT_ACCOUNT` varchar(20) NOT NULL,
  `STUDENT_NAME` varchar(100) NOT NULL,
  `STUDENT_HP` varchar(20) DEFAULT NULL,
  `STUDENT_AGE` varchar(5) DEFAULT NULL,
  `STUDENT_GENDER` varchar(20) DEFAULT NULL,
  `STUDENT_CURRICULUM` varchar(20) DEFAULT NULL,
  `STUDENT_REGION` varchar(20) DEFAULT NULL,
  `STUDENT_GROUP` varchar(20) NOT NULL,
  `ALGORITHM_GRADE` varchar(20) DEFAULT NULL,
  `ALGORITHM_ACQUISITION_DATE` datetime DEFAULT NULL,
  `REG_DT` datetime DEFAULT NULL,
  `LAST_DT` datetime DEFAULT NULL,
  FOREIGN KEY (TEACHER_CODE) REFERENCES TEACHER (TEACHER_CODE),
  FOREIGN KEY (TEAM_CODE) REFERENCES PROJECT (TEAM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE IF NOT EXISTS `ATTENDANCE` (
  `STUDENT_CODE` varchar(20) NOT NULL,
  `ATTENDANCE_DATE` date NOT NULL,
  `ATTENDANCE` tinyint(1) DEFAULT NULL,
  `ATTENDANCE_SIGN_IN` datetime DEFAULT NULL,
  `ATTENDANCE_SIGN_OUT` datetime DEFAULT NULL,
  FOREIGN KEY (STUDENT_CODE) REFERENCES STUDENT (STUDENT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE IF NOT EXISTS `EXAM` (
  `STUDENT_CODE` varchar(20) NOT NULL,
  `EXAM_CODE` VARCHAR(20) NOT NULL,
  `EXAM_SCORE` varchar(3) DEFAULT NULL,
  FOREIGN KEY (STUDENT_CODE) REFERENCES STUDENT (STUDENT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;
